#!/bin/sh

init() {
    if [ -f "./_zettel.json" ]; then
        echo '_zettel.json already exists'
        exit 1
    fi
    now=$(date --iso-8601=seconds)
    jq >_zettel.json <<EOF
{
    "meta": {
        "created": "$now",
        "modified": "$now"
    },
    "zettels": {}
}
EOF
    echo "initalized new zk metadatabase at ./_zettel.json"
}

usage() {
    cat >&1 <<EOM
invalid use!
EOM
}

new() {
    now=$(date --iso-8601=seconds)
    date=$(date '+%Y-%m-%d')
    if [ -z "$1" ]
        then title="my note"
        else title=$1
    fi
    escaped_title=$(echo "$title" | sed -e 's/\s/-/g')
    file_suffix="md"
    path="$date-$escaped_title.$file_suffix"
    uuid=$(uuid)
    if [ -f "$path" ]; then
        echo "$path exists"
        exit 1
    fi
    cat >"$path" <<EOF
---
uuid: "$uuid"
title: "$title"
---

EOF
    metadata=$(jq -r <<EOF
{
    "created": "$now",
    "modified": "$now",
    "path": "$path"
}
EOF
)
    update_metadata ".zettels.\"$uuid\"" "$metadata"
    update_metadata ".meta.modified" "\"$now\""
    echo "created a new zettel at $path"
}

update_metadata() {
    tmp=$(mktemp)
    # shellcheck disable=SC2064
    trap "rm $tmp" EXIT
    now=$(date --iso-8601=seconds)
    jq "$1  |= $2" _zettel.json >"$tmp"
    jq <"$tmp" >_zettel.json
}

update() {
    for zettel in ./*; do
        if ! echo "$zettel" | grep -q '_zettel\.json'; then
            start=$(grep -n -m 1 '^---$' "$zettel" | cut -d : -f 1)
            end=$(grep -n -m 2 '^---$' "$zettel" | tail -n 1 | cut -d : -f 1)
            uuid=$(tail -n "+$(($start + 1))" <"$zettel" | head -n "+$(($end - $start - 1))" | yj | jq -r '.uuid')
            path=$(jq -r ".zettels.\"$uuid\".path" ./_zettel.json)
            newpath=$(basename "$zettel")
            if [ ! "$path" = "$newpath" ]; then
                update_metadata ".zettels.\"$uuid\".path" "\"$newpath\""
                echo "$path -> $newpath"
            fi
            now=$(date --iso-8601=seconds)
            update_metadata ".meta.modified" "\"$now\""
        fi
    done
}

case "$1" in
    'init') init
    ;;
    'new') new "$2"
    ;;
    'update') update
    ;;
    *) usage
    ;;
esac
